name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Configura o GitHub Pages
      - uses: actions/configure-pages@v3

      # Empacota tudo na raiz para deploy
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .

      # Publica na Pages
      - uses: actions/deploy-pages@v1
